//! La vie privée : ce que le site et l'application ne font pas, et ce qu'ils
//! gardent — clé par clé dans le navigateur, fichier par fichier sur le
//! téléphone et sur l'hôte.
//!
//! Des données, pas du balisage : `crate::doc` est le seul rendu, et une
//! traduction manquante ne compile pas.

use crate::doc::{Block, DlItem, Doc, Tone};

pub static PRIVACY_EN: Doc = Doc {
    title: "Privacy",
    lede: "What this site collects, in full: nothing. Here is what that means concretely, what your browser keeps on its own, and what the app keeps on your phone.",
    blocks: &[
        Block::P("Most privacy pages describe what is collected and why it is fine. This one describes an absence, which is shorter and easier to verify — and verifiable is the point, because a claim nobody can check is worth nothing."),
        Block::P("It covers two different things. The site you are reading is a set of files served from one address, and it loads nothing from anywhere else. The app talks to the machines you name, and to nobody else. Where a claim can be checked, the page says how — a file in the repository, a test that fails if the sentence stops being true, or something you can look at on your own device."),
        Block::H2("No analytics, no cookies, no third parties"),
        Block::P("There is no analytics script, no tag manager, no embedded video, no web font from someone else's server, and no social widget. Neither the pages nor this project's server set a cookie of any kind — not for measurement and not for preferences."),
        Block::P("What a visit downloads is short to list: pre-rendered HTML, one stylesheet, one font file, a WebAssembly module and the JavaScript loader that starts it, the service worker, a manifest and the icons — all from this same address. The typeface, Archivo, is a file of the site itself, published under the SIL Open Font License, not a request to a font service. The tab icon is drawn inline, inside the page."),
        Block::P("That is not a promise on our word. The site's tests read the built files and fail if a page loads a script, a stylesheet, an image or a frame from an http or https address, or if the stylesheet or a script imports or fetches anything from one — site/tests/build.test.ts, which runs on every pull request and every push to master. You can confirm it yourself: open the developer tools, reload, and look at what was requested."),
        Block::P("The only other sites involved are the ones you choose to go to: the links to the source on GitHub, for instance. Nothing is loaded from them before you click, and what GitHub sees once you are there is governed by GitHub."),
        Block::H2("What your browser stores locally"),
        Block::P("Four small values, on your device, under names that begin with wisq. None of them is a cookie, and none travels with your requests: local storage and session storage stay in the browser, readable by this site's pages and by nobody else. None identifies you — each records a choice you made, or that an animation has already played."),
        Block::Table {
            columns: &["Key", "Holds", "Written when", "Goes away when"],
            rows: &[
                &["wisq.theme (local storage)", "light or dark", "You pick Light or Dark in the theme switch. Picking Match system deletes the key rather than storing a third value.", "You pick Match system, or clear the site's data."],
                &["wisq.lang (local storage)", "en or fr", "You click EN or FR in the header.", "You clear the site's data."],
                &["wisq.install.dismissed (local storage)", "A marker that means yes", "You tap Not now on the install banner, or answer the browser's own install prompt.", "You clear the site's data."],
                &["wisq.rideau (session storage)", "A marker that means yes", "The first page you open in a tab, unless your system asks for reduced motion.", "The tab is closed: session storage ends with it."],
            ],
        },
        Block::Dl(&[
            DlItem { term: "wisq.theme", detail: "Read by a few lines in the head of every page, before the first paint, so that a reader who chose light on a dark system does not see a flash of dark on each navigation. Without it, the page follows your system." },
            DlItem { term: "wisq.lang", detail: "Decides one thing only: whether the English home page sends a French-speaking browser to the French one. Once you have picked a language, by clicking either, that redirection never happens again. No other page redirects." },
            DlItem { term: "wisq.install.dismissed", detail: "Stops the banner that offers to install the site from asking again on every page." },
            DlItem { term: "wisq.rideau", detail: "Decides whether the curtain bearing the mark lifts as the page opens: once per tab, not on every page." },
        ]),
        Block::P("If storage is refused — a private window, a browser policy, a full quota — the site works exactly the same. What is lost is only that a choice survives to the next page; the page itself never depends on it."),
        Block::H3("The offline copy"),
        Block::P("The service worker keeps its own copy of the site, so that it opens with no network. When it installs, it stores every page in both languages — the not-found page aside — along with the stylesheet, the font, the WebAssembly module and its loader, the manifest and the icons. After that, each page that loads successfully from the network refreshes its copy. It only ever handles requests to this site's own address; a request anywhere else, it does not touch. When a new version of the site arrives, the previous cache is deleted."),
        Block::P("Your browser's ordinary HTTP cache keeps copies too, as it does for any site: files named after their content are marked as never changing, and everything else is checked with the server before it is reused."),
        Block::P("Clearing the site's data in your browser removes all of it — the four values and the offline copy. Nothing is restored from anywhere, because nothing left."),
        Block::H2("What the page reads about your browser"),
        Block::P("A few facts about your browser are read on your device to decide what to show. They are used where they are read and go no further: the page sends none of them anywhere, and the site has no code that reports anything back. Your browser does send its user agent with every request, on its own and to every site — that is the next section."),
        Block::Ul(&[
            "Your browser's preferred language — on the English home page only, and only if you have never picked a language. If it begins with fr, the page replaces itself with the French home page.",
            "Whether the site is already running installed, and whether the device is an iPhone, an iPad or an iPod, from its user agent and its touch points — to decide which install wording to show, if any.",
            "Whether your system asks for reduced motion: if it does, the entrance animation and the curtain do not play.",
            "Whether your system is in light or dark mode, through the stylesheet alone, when no theme is stored.",
        ]),
        Block::H2("What the host sees"),
        Block::P("The site is served by Heroku. Heroku's router receives every request before this project's server does, and the encrypted HTTPS connection ends there; the request then travels on inside Heroku's own platform. So Heroku sees what any web server sees, in full: an IP address, a user agent, and which files were asked for."),
        Block::P("What this project's server does with a request is in site/scripts/serve.ts, and it is short. It reads the path, to find the file. It reads the host the request arrived on, and the X-Forwarded-Proto header Heroku adds, to write the site's own address into the canonical links, the sitemap and robots.txt. It sets no cookie, keeps nothing from one request to the next, and writes no line per request — it prints a single one when it starts."),
        Block::P("What Heroku records about those requests, and for how long, is Heroku's, governed by Heroku's privacy statement, and outside what this project controls; this page does not guess at it. It is stated here rather than omitted because omitting it would make the paragraphs above misleading."),
        Block::H2("The app is a separate matter"),
        Block::P("wisq itself sends nothing to us either — there is no account, no telemetry, no analytics, no crash reporting, and no server of ours anywhere in the path. The Swift package declares no third-party dependency, and the Rust interpreter linked into the app declares none either, so no third-party SDK sits inside it to do any of that. It talks to machines you already have, on addresses you type in, import from a connection file, or receive in a pairing link. Passwords live in the iPhone Keychain; the machine list is plain JSON on your device and contains no secret."),
        Block::Note { tone: Tone::Warn, text: "One honest caveat about the app: plain TCP is a machine's default transport, so it speaks to that machine in the clear, and on an untrusted network that traffic is readable. It is a default, not a limit — the editor offers TLS, and TLS pinned to a certificate fingerprint, machine by machine, and it says under the picker which one a given machine will get. The host agent is a separate matter and speaks TLS on its own: a self-signed certificate whose SHA-256 travels in the pairing link and is pinned by the app." },
        Block::P("One channel sits outside the app: crash reports that iOS itself shares with developers, if you allowed it in the system's settings, go through Apple and follow those settings. There is no code for it in wisq, and the app keeps no log of its own."),
        Block::H3("What it keeps on the phone, and where"),
        Block::P("Everything lives in the app's own container on the phone, except the secrets, which go to the Keychain. The paths below start from that container's Application Support folder."),
        Block::Table {
            columns: &["What", "Where", "What is in it"],
            rows: &[
                &["The machine list", "Wisq/machines.json", "For each machine: its name, address, port and protocol, the encryption chosen and any certificate fingerprint to pin, the username if the protocol takes one, display and input settings, tags, when it was created and last connected, and the agent it is bound to. No password and no token: only a reference to the Keychain entry."],
                &["Passwords and agent tokens", "The iOS Keychain", "One entry per machine password, and one per agent token — shared by every VM on that agent. Readable once the phone has been unlocked after starting, so that a reconnection in the background works, and tied to this device: not synced through iCloud, and not carried to another phone."],
                &["Local machine settings", "Wisq/kernel-memory.json and Wisq/kernel-disk.json", "The memory size chosen for each kernel, and which disk image goes with it."],
                &["Imported images", "Wisq/kernels", "The kernels, initramfs, installation images and disk images you import, copied in under their own names. A disk image is never modified: what the guest writes goes elsewhere."],
                &["Disk writes", "Wisq/disk-writes", "What a guest wrote to a disk image, sector by sector, kept beside the image rather than in it. Deleted when the image is deleted."],
                &["Suspended machines", "Wisq, one .wisqvm file per kernel", "A snapshot of the whole machine — its memory included — taken when iOS sends the app to the background, so that the shell comes back where it was. Deleted with its kernel."],
                &["Unpacked installation image", "Wisq/iso", "The kernel and initramfs taken out of the last installation image booted. Replaced on every such boot."],
            ],
        },
        Block::P("Two consequences are worth saying plainly. A suspended machine is the guest's memory, so it holds whatever the guest held — a password typed inside it included. And nothing in wisq excludes these files from the phone's backups."),
        Block::P("The local machine screen has a Storage section that shows what kernels, saved machines and unpacked images take, and gives back what kernels deleted by earlier versions left behind. Deleting a machine from the list removes its password from the Keychain, and its agent's token once no other machine uses that agent. A connection file is read, shown in the editor, and saved only if you save it; the file itself is not copied. A .vv file's password goes to the Keychain; the saved password inside an .rdp file is not decoded, stored or carried — it is encrypted to the computer that wrote the file."),
        Block::H3("What it sends, and to whom"),
        Block::P("Only to hosts you have configured, and only for these:"),
        Block::Ul(&[
            "The console session — VNC, SPICE or RDP — to the address and port of the machine you open: the screen one way, your touches and keys the other.",
            "Requests to a host agent you paired with: listing its VMs and their state, starting one, stopping one, with the agent's token in each request.",
            "The clipboard, in a VNC or SPICE session: text copied in the guest is put on the iPhone's clipboard, and the iPhone's clipboard goes to the guest only when you tap the clipboard button.",
            "A file, in a SPICE session, only when you pick one with the send button.",
            "On the import screen, the app listens for agents announcing themselves on the local network over Bonjour. It announces nothing itself.",
        ]),
        Block::P("The local machines are the other way round: they run on the phone and have no emulated network card, so nothing a guest does reaches the network."),
        Block::H3("Encryption, connection by connection"),
        Block::P("The warning above, in detail. For every protocol, the editor's encryption picker offers no encryption, TLS, or TLS pinned to a certificate fingerprint; no encryption is the default."),
        Block::Table {
            columns: &["Connection", "On the wire", "The password or token"],
            rows: &[
                &["VNC", "Unencrypted unless TLS is chosen: the screen and every keystroke travel readable.", "Not sent as such — the server's challenge is answered with DES — but that scheme is weak by the protocol's own design."],
                &["SPICE", "Unencrypted unless TLS is chosen: the screen, the clipboard and files travel readable.", "Encrypted to the server's public key (RSA-OAEP), but without TLS nothing proves that key is the server's."],
                &["RDP", "Encrypted by the protocol's historic security (RC4) even without TLS — but that security does not authenticate the server: anyone on the path can sit in the middle.", "Sent inside that encryption, so no better protected than it is."],
                &["Host agent", "TLS by default, pinned to the certificate whose fingerprint the pairing link carried.", "The token travels inside that TLS. A link with no fingerprint — an agent started with --no-tls — means unencrypted HTTP, with the token still required."],
            ],
        },
        Block::P("TLS, when chosen, wraps the whole connection from its first byte, so the other end has to speak TLS from the start — a SPICE server's TLS port does, and so does a TLS tunnel placed in front of a server. wisq does not negotiate the protocols' own in-band encryption: VeNCrypt is not among the VNC security types it picks, and an RDP server that requires TLS or NLA is refused by name rather than worked around."),
        Block::P("Pinning a console's certificate means typing its SHA-256 fingerprint into the editor — openssl or a browser shows it. With no fingerprint, TLS pinned is ordinary TLS validated by the system, and the editor says so under the picker. Recording a fingerprint from the first connection is on the roadmap, not in the app."),
        Block::H3("The host agent, on your machine"),
        Block::P("wisq-agent is a small daemon you install on the computer that runs your VMs, so that the phone can start one before connecting. It has no account and contacts no server; what it keeps lives in ~/.wisq-agent, a directory and files readable by their owner alone."),
        Block::Dl(&[
            DlItem { term: "token", detail: "The bearer token: 32 characters drawn from the system's random source at first start, unless you pass --token. Every request must carry it. To revoke it, delete the file and restart the daemon — it reads the token once, at start, so deleting the file under a running daemon changes nothing." },
            DlItem { term: "tls-certificate.der and tls-key.der", detail: "The self-signed certificate and its private key (ECDSA P-256), made at first start. The certificate's SHA-256 is the fingerprint the pairing link carries and the app pins. It never rotates on its own; deleting both files is the rotation, and it invalidates every link printed before, on purpose." },
        ]),
        Block::P("At start-up the agent prints its token, its certificate fingerprint and one pairing link per network interface — the token is inside each link — plus a QR code of the first link when qrencode is installed. After that it prints nothing per request. So wherever its output goes — a terminal, journald, a log file — the token goes too, and that log deserves the care the token file gets."),
        Block::P("It listens on port 7442 by default, on every IPv4 address of the machine, and announces itself on the local network over Bonjour, under the machine's host name, when avahi-publish-service or dns-sd is present. The pairing link is the whole credential: whoever holds it can list your VMs, start them and power them off. Share it, or let someone photograph its QR code, only where you would share a password."),
        Block::H3("What it declares to iOS"),
        Block::P("An iOS app has to declare in its Info.plist what it will ask the system for. wisq's is generated from project.yml, and site/tests/info-plist.test.ts checks that the two agree. It declares:"),
        Block::Ul(&[
            "Local network access, with the sentence iOS shows when it asks, in French: “wisq se connecte aux machines de votre réseau local pour afficher leur écran.” Without it, iOS lets the app reach no machine on your network.",
            "Two Bonjour service types it may look for, _rfb._tcp and _wisq-agent._tcp. The app's code browses for the second, the agents.",
            "The wisq:// address scheme, which is how a pairing link — or the QR code that carries one — opens the app.",
        ]),
        Block::P("It declares no usage description for the camera, the microphone, location, contacts or the photo library — the declarations iOS requires before an app may ask for any of them. The QR code the agent prints is read by the iPhone's own camera, which hands the wisq:// link to wisq; wisq never sees the camera. SPICE can carry a microphone to the guest, and the protocol layer implements that channel, but nothing in the app opens the microphone."),
        Block::H2("Reporting a security problem"),
        Block::P("Not in a public issue. SECURITY.md asks for a private report through GitHub's “Report a vulnerability” form, under the Security tab of the repository, github.com/maxlestage/wisq, and says to expect a first answer within a week."),
        Block::P("It names what is most worth reporting: anything about how the agent handles its token, a way around its authentication, or abuse of its HTTP parser; anything that leaks a VNC password further than the protocol already does; and, for the local rv32ima interpreter, any way for a guest to corrupt the interpreter's memory outside its own RAM, or to step outside the machine."),
        Block::H2("Changes, and how to ask"),
        Block::P("If any of this ever stops being true, it changes here first and in the changelog at the same time. If something on this page is unclear or looks wrong — and is not a security problem — open an issue: that is a better outcome for everyone than a quiet assumption."),
    ],
};

pub static PRIVACY_FR: Doc = Doc {
    title: "Confidentialité",
    lede: "Ce que ce site collecte, en entier : rien. Voici ce que cela signifie concrètement, ce que votre navigateur conserve de lui-même, et ce que l'application garde sur votre téléphone.",
    blocks: &[
        Block::P("La plupart des pages de confidentialité décrivent ce qui est collecté et pourquoi ce n'est pas grave. Celle-ci décrit une absence, ce qui est plus court et plus facile à vérifier — et la vérifiabilité est justement le sujet, car une affirmation que personne ne peut contrôler ne vaut rien."),
        Block::P("Elle couvre deux choses distinctes. Le site que vous lisez est un ensemble de fichiers servis depuis une seule adresse, et il ne charge rien d'ailleurs. L'application parle aux machines que vous désignez, et à personne d'autre. Là où une affirmation peut se vérifier, la page dit comment — un fichier du dépôt, un test qui échoue si la phrase cesse d'être vraie, ou quelque chose que vous pouvez regarder sur votre propre appareil."),
        Block::H2("Aucune mesure d'audience, aucun cookie, aucun tiers"),
        Block::P("Il n'y a pas de script de mesure, pas de gestionnaire de balises, pas de vidéo intégrée, pas de police web servie par quelqu'un d'autre, pas de widget social. Ni les pages ni le serveur de ce projet ne déposent de cookie, d'aucune sorte — ni pour mesurer, ni pour des préférences."),
        Block::P("Ce qu'une visite télécharge se liste vite : du HTML pré-rendu, une feuille de style, un fichier de police, un module WebAssembly et le chargeur JavaScript qui le démarre, le service worker, un manifeste et les icônes — tout depuis cette même adresse. La police, Archivo, est un fichier du site lui-même, publié sous la licence SIL Open Font License, et non une requête à un service de polices. L'icône d'onglet est dessinée dans la page même."),
        Block::P("Ce n'est pas une promesse sur parole. Les tests du site lisent les fichiers construits et échouent si une page charge un script, une feuille de style, une image ou un cadre depuis une adresse http ou https, ou si la feuille de style ou un script importe ou va chercher quoi que ce soit à une telle adresse — site/tests/build.test.ts, qui tourne à chaque pull request et à chaque push sur master. Vous pouvez le constater vous-même : ouvrez les outils de développement, rechargez, et regardez ce qui a été demandé."),
        Block::P("Les seuls autres sites en jeu sont ceux où vous choisissez d'aller : les liens vers le code source sur GitHub, par exemple. Rien n'en est chargé avant que vous ne cliquiez, et ce que GitHub voit une fois que vous y êtes relève de GitHub."),
        Block::H2("Ce que votre navigateur garde en local"),
        Block::P("Quatre petites valeurs, sur votre appareil, sous des noms qui commencent par wisq. Aucune n'est un cookie, et aucune ne voyage avec vos requêtes : le stockage local et le stockage de session restent dans le navigateur, lisibles par les pages de ce site et par personne d'autre. Aucune ne vous identifie — chacune retient un choix que vous avez fait, ou qu'une animation a déjà été jouée."),
        Block::Table {
            columns: &["Clé", "Contenu", "Écrite quand", "Disparaît quand"],
            rows: &[
                &["wisq.theme (stockage local)", "light ou dark", "Vous choisissez Clair ou Sombre dans le sélecteur de thème. Choisir Selon le système efface la clé plutôt que de ranger une troisième valeur.", "Vous choisissez Selon le système, ou effacez les données du site."],
                &["wisq.lang (stockage local)", "en ou fr", "Vous cliquez sur EN ou FR dans l'en-tête.", "Vous effacez les données du site."],
                &["wisq.install.dismissed (stockage local)", "Un marqueur qui veut dire oui", "Vous touchez Plus tard sur la bannière d'installation, ou répondez à l'invite d'installation du navigateur lui-même.", "Vous effacez les données du site."],
                &["wisq.rideau (stockage de session)", "Un marqueur qui veut dire oui", "La première page que vous ouvrez dans un onglet, sauf si votre système demande moins d'animations.", "L'onglet est fermé : le stockage de session s'en va avec lui."],
            ],
        },
        Block::Dl(&[
            DlItem { term: "wisq.theme", detail: "Lu par quelques lignes en tête de chaque page, avant la première peinture, pour qu'un lecteur qui a choisi le clair sur un système sombre ne voie pas un éclair de sombre à chaque navigation. Sans lui, la page suit votre système." },
            DlItem { term: "wisq.lang", detail: "Ne décide qu'une chose : si l'accueil anglais envoie un navigateur francophone vers l'accueil français. Dès que vous avez choisi une langue, en cliquant sur l'une ou l'autre, cette redirection n'a plus jamais lieu. Aucune autre page ne redirige." },
            DlItem { term: "wisq.install.dismissed", detail: "Empêche la bannière qui propose d'installer le site de redemander à chaque page." },
            DlItem { term: "wisq.rideau", detail: "Décide si le rideau qui porte la marque se lève à l'ouverture de la page : une fois par onglet, pas à chaque page." },
        ]),
        Block::P("Si le stockage est refusé — une fenêtre de navigation privée, une politique du navigateur, un quota atteint —, le site fonctionne exactement de la même façon. Ce qui se perd, c'est seulement la survie d'un choix à la page suivante ; la page elle-même n'en dépend jamais."),
        Block::H3("La copie hors ligne"),
        Block::P("Le service worker garde sa propre copie du site, pour qu'il s'ouvre sans réseau. À son installation, il range chaque page dans les deux langues — la page d'adresse introuvable mise à part —, avec la feuille de style, la police, le module WebAssembly et son chargeur, le manifeste et les icônes. Ensuite, chaque page chargée avec succès depuis le réseau rafraîchit sa copie. Il ne traite jamais que les requêtes vers l'adresse de ce site ; une requête vers ailleurs, il n'y touche pas. Quand une nouvelle version du site arrive, le cache précédent est supprimé."),
        Block::P("Le cache HTTP ordinaire de votre navigateur garde aussi des copies, comme pour n'importe quel site : les fichiers nommés d'après leur contenu sont marqués comme ne changeant jamais, et tout le reste est revérifié auprès du serveur avant d'être réutilisé."),
        Block::P("Effacer les données du site dans votre navigateur retire l'ensemble — les quatre valeurs et la copie hors ligne. Rien n'est restauré depuis ailleurs, puisque rien n'en est parti."),
        Block::H2("Ce que la page lit de votre navigateur"),
        Block::P("Quelques faits sur votre navigateur sont lus sur votre appareil pour décider quoi afficher. Ils servent là où ils sont lus et ne vont pas plus loin : la page n'en envoie aucun nulle part, et le site n'a aucun code qui rende compte de quoi que ce soit. Votre navigateur, lui, envoie son agent utilisateur avec chaque requête, de lui-même et à tous les sites — c'est la section suivante."),
        Block::Ul(&[
            "La langue préférée de votre navigateur — sur l'accueil anglais seulement, et seulement si vous n'avez jamais choisi de langue. Si elle commence par fr, la page se remplace par l'accueil français.",
            "Si le site tourne déjà installé, et si l'appareil est un iPhone, un iPad ou un iPod, d'après son agent utilisateur et ses points de contact — pour décider quelle formulation d'installation montrer, s'il y en a une.",
            "Si votre système demande moins d'animations : dans ce cas, l'animation d'entrée et le rideau ne se jouent pas.",
            "Si votre système est en mode clair ou sombre, par la seule feuille de style, quand aucun thème n'est rangé.",
        ]),
        Block::H2("Ce que voit l'hébergeur"),
        Block::P("Le site est servi par Heroku. Le routeur d'Heroku reçoit chaque requête avant le serveur de ce projet, et c'est là que se termine la connexion HTTPS chiffrée ; la requête poursuit ensuite à l'intérieur de la plateforme d'Heroku. Heroku voit donc ce que voit n'importe quel serveur web, en entier : une adresse IP, un agent utilisateur, et les fichiers demandés."),
        Block::P("Ce que le serveur de ce projet fait d'une requête est dans site/scripts/serve.ts, et c'est court. Il lit le chemin, pour trouver le fichier. Il lit l'hôte sur lequel la requête est arrivée, et l'en-tête X-Forwarded-Proto qu'ajoute Heroku, pour écrire l'adresse du site dans les liens canoniques, le sitemap et robots.txt. Il ne pose aucun cookie, ne garde rien d'une requête à l'autre, et n'écrit aucune ligne par requête — il en imprime une seule au démarrage."),
        Block::P("Ce qu'Heroku consigne de ces requêtes, et pour combien de temps, lui appartient, relève de la politique de confidentialité d'Heroku, et échappe à ce que ce projet contrôle ; cette page ne le devine pas. C'est dit ici plutôt qu'omis, car l'omettre rendrait les paragraphes précédents trompeurs."),
        Block::H2("L'application est un sujet distinct"),
        Block::P("wisq ne nous envoie rien non plus — pas de compte, pas de télémétrie, pas de mesure d'audience, pas de rapport de plantage, aucun serveur à nous sur le chemin. Le paquet Swift ne déclare aucune dépendance tierce, et l'interprète Rust lié dans l'application n'en déclare aucune non plus : aucun SDK tiers ne s'y trouve donc pour faire quoi que ce soit de cela. L'application parle à des machines que vous possédez déjà, sur des adresses que vous saisissez, importez d'un fichier de connexion ou recevez dans un lien d'appairage. Les mots de passe vivent dans le trousseau de l'iPhone ; la liste des machines est du JSON sur votre appareil et ne contient aucun secret."),
        Block::Note { tone: Tone::Warn, text: "Une réserve honnête sur l'application : le TCP en clair est le transport par défaut d'une machine, et sur un réseau non fiable ce trafic est lisible. C'est un défaut, pas une limite — l'éditeur propose TLS, et TLS épinglé par empreinte de certificat, machine par machine, et il dit sous le sélecteur ce qu'une machine donnée obtiendra. Le démon hôte est un cas à part et parle TLS de lui-même : un certificat auto-signé dont l'empreinte SHA-256 voyage dans le lien d'appairage et que l'application épingle." },
        Block::P("Un canal se trouve hors de l'application : les rapports de plantage qu'iOS partage lui-même avec les développeurs, si vous l'avez autorisé dans les réglages du système, passent par Apple et suivent ces réglages. wisq n'a aucun code pour cela, et l'application ne tient aucun journal de son côté."),
        Block::H3("Ce qu'elle garde sur le téléphone, et où"),
        Block::P("Tout vit dans le conteneur de l'application sur le téléphone, sauf les secrets, qui vont au trousseau. Les chemins ci-dessous partent du dossier Application Support de ce conteneur."),
        Block::Table {
            columns: &["Quoi", "Où", "Ce qu'il contient"],
            rows: &[
                &["La liste des machines", "Wisq/machines.json", "Pour chaque machine : son nom, son adresse, son port et son protocole, le chiffrement choisi et l'empreinte de certificat à épingler s'il y en a une, le nom d'utilisateur si le protocole en prend un, les réglages d'affichage et de saisie, les étiquettes, les dates de création et de dernière connexion, et l'agent auquel elle est liée. Aucun mot de passe ni aucun jeton : seulement une référence vers l'entrée du trousseau."],
                &["Mots de passe et jetons d'agent", "Le trousseau iOS", "Une entrée par mot de passe de machine, et une par jeton d'agent — partagée par toutes les VM de cet agent. Lisibles dès que le téléphone a été déverrouillé une fois après son démarrage, pour qu'une reconnexion en arrière-plan fonctionne, et attachées à cet appareil : ni synchronisées par iCloud, ni transportées vers un autre téléphone."],
                &["Réglages des machines locales", "Wisq/kernel-memory.json et Wisq/kernel-disk.json", "La taille de mémoire choisie pour chaque noyau, et l'image disque qui va avec."],
                &["Images importées", "Wisq/kernels", "Les noyaux, initramfs, images d'installation et images disque que vous importez, copiés sous leur propre nom. Une image disque n'est jamais modifiée : ce que l'invité écrit va ailleurs."],
                &["Écritures sur disque", "Wisq/disk-writes", "Ce qu'un invité a écrit sur une image disque, secteur par secteur, rangé à côté de l'image plutôt que dedans. Supprimé quand l'image est supprimée."],
                &["Machines suspendues", "Wisq, un fichier .wisqvm par noyau", "Un instantané de la machine entière — sa mémoire comprise —, pris quand iOS envoie l'application en arrière-plan, pour que le shell revienne là où il était. Supprimé avec son noyau."],
                &["Image d'installation déballée", "Wisq/iso", "Le noyau et l'initramfs sortis de la dernière image d'installation démarrée. Remplacés à chaque démarrage de ce genre."],
            ],
        },
        Block::P("Deux conséquences méritent d'être dites franchement. Une machine suspendue est la mémoire de l'invité : elle contient ce que l'invité contenait — un mot de passe tapé dedans compris. Et rien dans wisq n'exclut ces fichiers des sauvegardes du téléphone."),
        Block::P("L'écran de la machine locale a une section Stockage qui montre ce que prennent les noyaux, les machines sauvegardées et les images déballées, et qui reprend ce que des noyaux supprimés par des versions antérieures avaient laissé. Supprimer une machine de la liste retire son mot de passe du trousseau, et le jeton de son agent dès qu'aucune autre machine n'emploie cet agent. Un fichier de connexion est lu, montré dans l'éditeur, et enregistré seulement si vous l'enregistrez ; le fichier lui-même n'est pas copié. Le mot de passe d'un .vv va au trousseau ; celui qu'un .rdp sauvegarde n'est ni décodé, ni rangé, ni transporté — il est chiffré pour l'ordinateur qui a écrit le fichier."),
        Block::H3("Ce qu'elle envoie, et à qui"),
        Block::P("Seulement aux hôtes que vous avez configurés, et seulement pour ceci :"),
        Block::Ul(&[
            "La session de console — VNC, SPICE ou RDP — vers l'adresse et le port de la machine que vous ouvrez : l'écran dans un sens, vos touchers et vos touches dans l'autre.",
            "Les requêtes à un agent hôte appairé : lister ses VM et leur état, en démarrer une, en arrêter une, avec le jeton de l'agent dans chaque requête.",
            "Le presse-papiers, dans une session VNC ou SPICE : un texte copié dans l'invité est posé sur le presse-papiers de l'iPhone, et celui de l'iPhone ne part vers l'invité que quand vous touchez le bouton presse-papiers.",
            "Un fichier, dans une session SPICE, seulement quand vous en choisissez un avec le bouton d'envoi.",
            "Sur l'écran d'import, l'application écoute les agents qui s'annoncent sur le réseau local par Bonjour. Elle-même n'annonce rien.",
        ]),
        Block::P("Les machines locales sont l'inverse : elles tournent sur le téléphone et n'ont pas de carte réseau émulée, donc rien de ce que fait un invité n'atteint le réseau."),
        Block::H3("Le chiffrement, connexion par connexion"),
        Block::P("La réserve ci-dessus, en détail. Pour chaque protocole, le sélecteur de chiffrement de l'éditeur propose de ne rien chiffrer, TLS, ou TLS épinglé par empreinte de certificat ; ne rien chiffrer est le défaut."),
        Block::Table {
            columns: &["Connexion", "Sur le fil", "Le mot de passe ou le jeton"],
            rows: &[
                &["VNC", "Sans chiffrement tant que TLS n'est pas choisi : l'écran et chaque touche circulent lisibles.", "Pas envoyé tel quel — le défi du serveur reçoit une réponse chiffrée par DES —, mais ce mécanisme est faible par la conception même du protocole."],
                &["SPICE", "Sans chiffrement tant que TLS n'est pas choisi : l'écran, le presse-papiers et les fichiers circulent lisibles.", "Chiffré pour la clé publique du serveur (RSA-OAEP), mais sans TLS rien ne prouve que cette clé est bien celle du serveur."],
                &["RDP", "Chiffré par la sécurité historique du protocole (RC4) même sans TLS — mais celle-ci n'authentifie pas le serveur : n'importe qui sur le chemin peut se placer au milieu.", "Envoyé à l'intérieur de ce chiffrement, donc pas mieux protégé que lui."],
                &["Démon hôte", "TLS par défaut, épinglé sur le certificat dont le lien d'appairage portait l'empreinte.", "Le jeton voyage dans ce TLS. Un lien sans empreinte — un démon lancé avec --no-tls — veut dire HTTP sans chiffrement, le jeton restant obligatoire."],
            ],
        },
        Block::P("TLS, quand il est choisi, enveloppe toute la connexion dès son premier octet : l'autre bout doit donc parler TLS d'emblée — le port TLS d'un serveur SPICE le fait, un tunnel TLS placé devant un serveur aussi. wisq ne négocie pas le chiffrement propre à chaque protocole : VeNCrypt ne fait pas partie des types de sécurité VNC qu'il choisit, et un serveur RDP qui exige TLS ou NLA est refusé par son nom plutôt que contourné."),
        Block::P("Épingler le certificat d'une console, c'est saisir son empreinte SHA-256 dans l'éditeur — openssl ou un navigateur l'affiche. Sans empreinte, TLS épinglé n'est qu'un TLS validé par le système, et l'éditeur le dit sous le sélecteur. Enregistrer l'empreinte dès la première connexion est sur la feuille de route, pas dans l'application."),
        Block::H3("Le démon hôte, sur votre machine"),
        Block::P("wisq-agent est un petit démon que vous installez sur l'ordinateur qui fait tourner vos VM, pour que le téléphone puisse en démarrer une avant de s'y connecter. Il n'a pas de compte et ne contacte aucun serveur ; ce qu'il garde vit dans ~/.wisq-agent, un dossier et des fichiers lisibles par leur seul propriétaire."),
        Block::Dl(&[
            DlItem { term: "token", detail: "Le jeton porteur : 32 caractères tirés de la source d'aléa du système au premier lancement, sauf si vous passez --token. Chaque requête doit le porter. Pour le révoquer, supprimez le fichier et relancez le démon — il lit le jeton une fois, au démarrage, donc supprimer le fichier sous un démon qui tourne ne change rien." },
            DlItem { term: "tls-certificate.der et tls-key.der", detail: "Le certificat auto-signé et sa clé privée (ECDSA P-256), créés au premier lancement. L'empreinte SHA-256 du certificat est celle que porte le lien d'appairage et que l'application épingle. Il ne tourne jamais de lui-même ; supprimer les deux fichiers est la rotation, et elle invalide à dessein tous les liens imprimés avant." },
        ]),
        Block::P("Au démarrage, le démon imprime son jeton, l'empreinte de son certificat et un lien d'appairage par interface réseau — le jeton est dans chaque lien —, plus un QR code du premier lien quand qrencode est installé. Ensuite, il n'imprime rien par requête. Partout où va sa sortie — un terminal, journald, un fichier journal —, le jeton va donc aussi, et ce journal mérite le soin qu'on accorde au fichier du jeton."),
        Block::P("Il écoute sur le port 7442 par défaut, sur toutes les adresses IPv4 de la machine, et s'annonce sur le réseau local par Bonjour, sous le nom d'hôte de la machine, quand avahi-publish-service ou dns-sd est présent. Le lien d'appairage est toute la clé : qui le détient peut lister vos VM, les démarrer et les éteindre. Ne le partagez, et ne laissez photographier son QR code, que là où vous partageriez un mot de passe."),
        Block::H3("Ce qu'elle déclare à iOS"),
        Block::P("Une application iOS doit déclarer dans son Info.plist ce qu'elle demandera au système. Celui de wisq est engendré depuis project.yml, et site/tests/info-plist.test.ts vérifie que les deux s'accordent. Il déclare :"),
        Block::Ul(&[
            "L'accès au réseau local, avec la phrase qu'iOS affiche en le demandant : « wisq se connecte aux machines de votre réseau local pour afficher leur écran. » Sans elle, iOS ne laisse l'application joindre aucune machine de votre réseau.",
            "Deux types de service Bonjour qu'elle peut chercher, _rfb._tcp et _wisq-agent._tcp. Le code de l'application cherche le second, celui des agents.",
            "Le schéma d'adresse wisq://, par lequel un lien d'appairage — ou le QR code qui en porte un — ouvre l'application.",
        ]),
        Block::P("Il ne déclare aucune justification d'usage pour l'appareil photo, le micro, la localisation, les contacts ou la photothèque — les déclarations qu'iOS exige avant qu'une application puisse demander l'un d'eux. Le QR code qu'imprime le démon est lu par l'appareil photo de l'iPhone lui-même, qui passe le lien wisq:// à wisq ; wisq ne voit jamais la caméra. SPICE peut porter un micro vers l'invité, et la couche protocole implémente ce canal, mais rien dans l'application n'ouvre le micro."),
        Block::H2("Signaler un problème de sécurité"),
        Block::P("Pas dans une issue publique. SECURITY.md demande un signalement privé par le formulaire « Report a vulnerability » de GitHub, sous l'onglet Security du dépôt, github.com/maxlestage/wisq, et annonce une première réponse dans la semaine."),
        Block::P("Il nomme ce qui mérite le plus d'être signalé : tout ce qui touche à la façon dont le démon traite son jeton, un moyen de contourner son authentification, ou un abus de son analyseur HTTP ; tout ce qui fait fuir un mot de passe VNC plus loin que le protocole ne le fait déjà ; et, pour l'interprète local rv32ima, tout moyen pour un invité de corrompre la mémoire de l'interprète hors de sa propre RAM, ou de sortir de la machine."),
        Block::H2("Changements, et comment demander"),
        Block::P("Si l'un de ces points cesse d'être vrai, cela change ici en premier et dans le journal des modifications en même temps. Si quelque chose sur cette page est flou ou paraît faux — et n'est pas un problème de sécurité —, ouvrez une issue : c'est un meilleur résultat pour tout le monde qu'une supposition silencieuse."),
    ],
};
